repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-added-large-files
      name: Check for large added files
      args: [--maxkb, "500"]
    - id: check-case-conflict
      name: Check for file system case conflicts
    - id: check-executables-have-shebangs
      name: Check for executables missing shebangs
    - id: check-json
      name: Check JSON validates
    - id: check-merge-conflict
      name: Check for merge conflicts
    - id: check-shebang-scripts-are-executable
      name: Check for non-executable scripts with shebangs
    - id: check-symlinks
      name: Check for broken symlinks
    - id: check-toml
      name: Check TOML validates
      exclude: ^{{cookiecutter.source_directory_name}}/
    - id: check-vcs-permalinks
      name: Check for GitHub permalinks
    - id: check-xml
      name: Check XML validates
    - id: check-yaml
      name: Check YAML validates
    - id: destroyed-symlinks
      name: Check for destroyed symlinks
    - id: end-of-file-fixer
      name: Check for missing newline at the end of files
    - id: fix-byte-order-marker
      name: Check for UTF-8 byte order marker
    - id: mixed-line-ending
      name: Check for mixed line endings
    - id: name-tests-test
      name: (Python) Check that test files end in _test.py
    - id: pretty-format-json
      name: Pretty format JSON
      args: [--autofix, --indent, "2"]
    - id: trailing-whitespace
      name: Check for trailing whitespace
      exclude: \.md$
